# Generated by Django 5.1.5 on 2025-07-05 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_profile_address_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('date_booked', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.boardinghouse')),
            ],
        ),
    ]
