# Generated by Django 5.1.5 on 2025-07-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_boardinghouse_is_booked_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
