# Generated by Django 5.1.5 on 2025-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_images/'),
        ),
    ]
