# Generated by Django 5.1.5 on 2025-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_boardinghouse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
