# Generated by Django 5.2.4 on 2025-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_boardinghouse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_permit',
            field=models.ImageField(blank=True, null=True, upload_to='business_permits/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
