# Generated by Django 5.1.5 on 2025-09-20 10:54

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_profile_business_permit_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='boardinghouse',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='boardinghouse',
            name='owner',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'Free Wi-Fi'), ('water', 'Free Water'), ('electric', 'Free Electric Bill')], max_length=19),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boardinghouses/'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
