# Generated by Django 5.1.5 on 2025-09-20 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_boardinghouse_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_images/'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
