# Generated by Django 5.1.5 on 2025-09-26 04:49

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_boardinghouse_is_booked_boardinghouse_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='additional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_images/'),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='house_rules',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('curfew', 'Curfew (10:00pm - 4:00am)'), ('advance', '1 Month Advance'), ('deposit', '1 Month Deposit'), ('lady_only', 'Lady Borders Only'), ('male_only', 'Male Borders Only'), ('visitors_allowed', 'Visitors Are Allowed'), ('appliances', 'Additional Appliances')], max_length=70),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='inclusions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('water', 'Water Bill'), ('electric', 'Electric Bill'), ('wifi', 'WiFi Connection')], max_length=19),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='other_amenities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='other_house_rules',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='other_inclusions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kitchen', 'Kitchen Area'), ('comfort_room', 'Comfort Room'), ('laundry', 'Laundry Area'), ('balcony', 'Balcony'), ('study', 'Study Area'), ('cctv', 'CCTV'), ('parking', 'Parking Space'), ('lockable_gate', 'Lockable Gate'), ('bedroom', 'Bedroom'), ('cabinet', 'Cabinet')], max_length=85),
        ),
    ]
