# Generated by Django 5.1.5 on 2025-09-26 05:10

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_boardinghouse_additional_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='advance_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='curfew_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='deposit_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='house_rules',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('curfew', 'Curfew (10:00pm - 4:00am)'), ('advance_payment', 'Advance Payment'), ('deposit', 'Deposit'), ('lady_only', 'Lady Borders Only'), ('male_only', 'Male Borders Only'), ('visitors_allowed', 'Visitors Are Allowed'), ('appliances', 'Additional Appliances')], max_length=78),
        ),
    ]
