# Generated by Django 5.1.5 on 2025-09-27 14:02

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_boardinghouse_advance_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='curfew_time',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='curfew_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='curfew_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='house_rules',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('curfew', 'Curfew'), ('advance_payment', 'Advance Payment'), ('deposit', 'Deposit'), ('lady_only', 'Lady Borders Only'), ('male_only', 'Male Borders Only'), ('visitors_allowed', 'Visitors Are Allowed'), ('appliances', 'Additional Appliances')], max_length=78),
        ),
    ]
