# Generated by Django 5.1.5 on 2025-09-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_remove_boardinghouse_curfew_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='boardinghouse',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_bedspacer', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('boardinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='client.boardinghouse')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.room'),
        ),
    ]
