# Generated by Django 5.1.5 on 2025-09-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_remove_booking_boardinghouse_room_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boardinghouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client.boardinghouse'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client.room'),
        ),
    ]
