# Generated by Django 5.1.5 on 2025-09-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_booking_boardinghouse_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='is_bedspacer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='boardinghouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.boardinghouse'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
