# Generated by Django 5.1.5 on 2025-09-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_remove_booking_room_boardinghouse_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='boardinghouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client.boardinghouse'),
        ),
    ]
