# Generated by Django 5.1.5 on 2025-09-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_booking_boardinghouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
