# Generated by Django 5.1.5 on 2025-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_booking_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
