# Generated by Django 5.1.5 on 2025-10-03 07:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='house_rules',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('curfew', 'Curfew'), ('advance_payment', 'Month/s Advance Payment'), ('deposit', 'Month/s Deposit'), ('lady_only', 'Lady Borders Only'), ('male_only', 'Male Borders Only'), ('visitors_allowed', 'Visitors Are Allowed'), ('appliances', 'Additional Appliances')], max_length=78),
        ),
    ]
